feat:增加镜像刷写文档
pixmoving-moveit/pixkit-documentation-cn pull request #15
Opened 2023-04-25 02:09 UTC by jackeyming

2023-04-25 15:15 UTC, ahuazuipiaoliang requested changes
1. 需要前面加入为什么需要备份镜像和使用镜像还原的原因和基本原则
2. 结尾最好还要加入`注意事项`和`参考资料`

2023-04-25 15:15 UTC, ahuazuipiaoliang commented on docs/支持/备份系统镜像.md
> +第六步：保存镜像文件至硬盘
```suggestion
#### 第六步
保存镜像文件至硬盘
```

2023-04-25 15:15 UTC, ahuazuipiaoliang commented on docs/支持/备份系统镜像.md
> +第七步：使用挂载设备时选择第一个
```suggestion
#### 第七步
使用挂载设备时选择正确的设备
```

2023-04-25 15:15 UTC, ahuazuipiaoliang commented on docs/支持/备份系统镜像.md
> +第九步：ctrl+c
```suggestion
#### 第九步：退出窗口
使用`ctrl+c`退出窗口
```

2023-05-05 08:33 UTC, zymouse commented
<img width="337" alt="image" src="https://user-images.githubusercontent.com/46778435/236411905-462b2d75-dc18-4593-9ce4-b98569ae639d.png">
和上面图片统一[中英文]：这几张图片只有中文，

2023-05-05 08:35 UTC, zymouse commented on docs/支持/刷写系统镜像.md
> +第一步：插入U盘，开机按住F12（可以使用有线键盘操作），进入刷机启动界面
### 第一步：插入U盘，开机按住F12（可以使用有线键盘操作），进入刷机启动界面

2023-05-06 07:55 UTC, ahuazuipiaoliang requested changes

2023-05-06 07:55 UTC, ahuazuipiaoliang commented on docs/支持/.pages
> +  - 刷写系统镜像.md
应该吧备份系统放到前面

2023-05-06 07:55 UTC, ahuazuipiaoliang commented on docs/支持/刷写系统镜像.md
标题没有层级，不好导航
可以将
·第一步：插入U盘，开机按住F12（可以使用有线键盘操作），进入刷机启动界面
改为
### 第一步：插入U盘，开机按住F12（可以使用有线键盘操作），进入刷机启动界面

2023-05-06 07:55 UTC, ahuazuipiaoliang commented on docs/支持/备份系统镜像.md
文档标题没有层级

2023-05-06 09:56 UTC, zymouse requested changes
大体没有问题，一些细节问题

2023-05-06 09:56 UTC, zymouse commented on docs/支持/备份系统镜像.md
> +### step-9：ctrl+c
```suggestion
### step-9：ctrl+c

> 等待出现硬盘信息(如下图)，才能按下`ctrl+c`

```

2023-05-06 09:56 UTC, zymouse commented on docs/支持/images/l9.png
<img width="601" alt="image" src="https://user-images.githubusercontent.com/46778435/236617153-5b993da2-16d5-435e-bc4e-fe9d5df8b1c9.png">
这样更好

2023-05-08 02:27 UTC, zymouse requested changes
添加引用，和启动盘制作方法

2023-05-08 02:27 UTC, zymouse commented on docs/支持/备份系统镜像.md
> +**注意事项**： U盘作为启动盘，需要保存自己镜像时候需要用户提供硬盘，不要在U盘上做任何修改、添加或者保存其他文件，以免破坏启动盘的环境。
```suggestion
**注意事项**： U盘作为启动盘，需要保存自己镜像时候需要用户提供硬盘，不要在U盘上做任何修改、添加或者保存其他文件，以免破坏启动盘的环境。

## 引用
[Clonezilla 再生龍](https://clonezilla.nchc.org.tw/intro/)
```

2023-05-08 02:27 UTC, zymouse commented on docs/支持/刷写系统镜像.md
> +**注意事项**： 此U盘建议仅用于还原镜像，不要做任何修改、添加或者保存其他文件，以免破坏启动盘的环境。
```suggestion
**注意事项**： 此U盘建议仅用于还原镜像，不要做任何修改、添加或者保存其他文件，以免破坏启动盘的环境。

## 引用
[Clonezilla 再生龍](https://clonezilla.nchc.org.tw/intro/)
```

2023-05-08 02:27 UTC, zymouse commented on docs/支持/刷写系统镜像.md
> +### step-1：插入U盘，开机按住F12（可以使用有线键盘操作），进入刷机启动界面
```suggestion
### step-1：插入`再生龙启动U盘`，开机按住F12（可以使用有线键盘操作），进入刷机启动界面
```

2023-05-08 02:27 UTC, zymouse commented on docs/支持/刷写系统镜像.md
> +### step-2：使用U盘还原镜像时选择第二个选项
```suggestion
### step-2：使用`再生龙启动U盘`还原镜像时选择第二个选项
```

2023-05-08 02:27 UTC, zymouse commented on docs/支持/备份系统镜像.md
> +### step-1：插入U盘，开机按住F12（可以使用有线键盘操作），进入刷机启动界面
```suggestion
### step-1：插入`再生龙启动U盘`，开机按住F12（可以使用有线键盘操作），进入刷机启动界面
```

2023-05-08 02:27 UTC, zymouse commented on docs/支持/备份系统镜像.md
> +### step-2：使用硬盘来作镜像
```suggestion
### step-2：使用一个新的`100G以上的移动硬盘`或者`100G以上的U盘`作为镜像文件存储盘
```

2023-05-08 02:27 UTC, zymouse commented on docs/支持/备份系统镜像.md
> +> 系统的最初镜像已附带在U盘里，用户需要添加备份镜像，则需要提供一个超过100G的硬盘
```suggestion
> 系统的出厂镜像已附带在`再生龙启动U盘`里，用户需要备份镜像，则需要重新准备一个`100G以上的移动硬盘`或者`100G以上的U盘`
```

2023-05-08 02:27 UTC, zymouse commented on docs/支持/刷写系统镜像.md
> +> 参考资料：<https://www.youtube.com/watch?v=YEFt2LPSYMk>
```suggestion
> 参考资料：<https://www.youtube.com/watch?v=YEFt2LPSYMk>
> [`再生龙启动U盘`制作方法](https://clonezilla.nchc.org.tw/clonezilla-live/liveusb.php#windows-method-b)
```

2023-05-08 02:27 UTC, zymouse commented on docs/支持/备份系统镜像.md
> +> 参考资料：<https://www.youtube.com/watch?v=8-7w5zwD9M4>
```suggestion
> 参考资料：<https://www.youtube.com/watch?v=8-7w5zwD9M4>
> [`再生龙启动U盘`制作方法](https://clonezilla.nchc.org.tw/clonezilla-live/liveusb.php#windows-method-b)
```

2023-05-08 02:53 UTC, ahuazuipiaoliang approved these changes
LGTM

2023-05-25 08:08 UTC, jackeyming commented
文档编写完成， @ahuazuipiaoliang @zymouse

2023-05-25 08:17 UTC, zymouse approved these changes
检查完毕

2023-05-25 08:20 UTC, merged