feat(pointcloud_map): update doc
pixmoving-moveit/pixkit-documentation-cn pull request #29
Opened 2023-05-23 11:49 UTC by ahuazuipiaoliang

更新点云地图制作文档，使用[LIO-SAM-ROS2-PIXKIT](https://github.com/pixmoving-moveit/LIO-SAM-ROS2-PIXKIT)

2023-05-24 06:54 UTC, zymouse requested changes

2023-05-24 06:54 UTC, zymouse commented on docs/地图/点云地图.md
> +![map-origin](./images/map-origin.jpg)
```suggestion
![map-origin](./images/map-origin.jpg)
> 建议把终端里的信息保存下来。方便用于GNSS定位时使用
```

2023-05-24 06:54 UTC, zymouse commented on docs/地图/images/map-origin.jpg
可以使用红框标注出来，比较醒目

2023-05-24 06:54 UTC, zymouse commented on docs/地图/点云地图.md
>  - IMU外参，参考[LiDAR与IMU外参标定](../%E4%BC%A0%E6%84%9F%E5%99%A8%E6%A0%87%E5%AE%9A/LiDAR-IMU%E6%A0%87%E5%AE%9A.md)
```suggestion
- IMU外参，参考[LiDAR与IMU外参标定](../%E4%BC%A0%E6%84%9F%E5%99%A8%E6%A0%87%E5%AE%9A/LiDAR-IMU%E6%A0%87%E5%AE%9A.md)

> IMU外参，可以使用[LiDAR与IMU外参标定]，也可以使用卷尺手动量取(坐标系为右手法则)
> 当手动量取时：
> - extrinsicTrans:卷尺手动量取
> - extrinsicRot: 单位矩阵即可

```

2023-05-24 07:25 UTC, ahuazuipiaoliang commented
@zymouse 已修改

2023-05-25 08:23 UTC, zymouse approved these changes
检查完毕，没有问题

2023-05-25 08:24 UTC, merged